- name: postmap sasl_passwd
  command: /usr/sbin/postmap hash:/etc/postfix/sasl_passwd

- name: postfix reload service
  service: name=postfix state=reloaded

- name: reload systemd
  command: systemctl daemon-reload

- name: running newaliases
  command: newaliases
