- hosts: all
  become: true
  become_user: root
  roles:
    - { role: apt, tags: apt }
    - { role: ansible, tags: ansible, mitogen: no }
  tasks:
    - name: "Configure temporary dpkg options" 
      copy:
        dest: /etc/apt/apt.conf.d/local
        mode: 0644
        content: 'DPkg::options { "--force-confold"; }'

    - name: "Disable ansible cron"
      file:
        name=/etc/cron.d/ansible
        state=absent

    - name: "Run apt-get dist-upgrade once for the current release"
      apt:
        upgrade: dist
        update_cache: yes
  tags:
    - prepare

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Remove automatic update files"
      file: name={{ item }} state=absent
      with_items:
        - /etc/apt/apt.conf.d/50unattended-upgrades
        - /etc/apt/apt.conf.d/50unattended-upgrades.dpkg-dist

    - name: "Perform release upgrade (xenial -> bionic)"
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: ansible_distribution_release == "xenial"

    - name: "Remove daemontools"
      apt: name={{ item }} state=absent
      with_items:
        - daemontools
  tags:
    - bionic

- hosts: all
  become: true
  become_user: root
  roles:
    - { role: apt, tags: apt }
    - { role: ansible, tags: ansible, mitogen: no }
  tasks:
    - name: "Remove temporary dpkg configuration" 
      file:
        name: /etc/apt/apt.conf.d/local
        state: absent

    - name: "Remove spurious automatic update file"
      file: name={{ item }} state=absent
      with_items:
        - /etc/apt/apt.conf.d/50unattended-upgrades.dpkg-dist

    - name: "Remove old virtual environments"
      file: name={{ item }} state=absent
      with_items:
        - /usr/share/ripe-atlas-venv
  tags:
    - cleanup

- hosts: ringnode
  become: true
  become_user: root
  roles:
    - { role: users, class: ring-users, tags: ring-users }
