#!/bin/bash

# This used to test if the executables were installed.  But that is
# perfectly redundant and supresses errors that the admin should see.

/usr/share/munin/munin-update $@ || exit 1

# The result of munin-limits is needed by munin-html but not by
# munin-graph.  So run it in the background now, it will be done
# before munin-graph.

/usr/share/munin/munin-limits $@

# We always launch munin-html.
# It is a noop if html_strategy is "cgi"
if [ "$((${RANDOM} % 10))" = "7" ]; then
    nice /usr/share/munin/munin-html $@ || exit 1
fi

# The result of munin-html is needed for munin-graph.
# It is a noop if graph_strategy is "cgi"
nice /usr/share/munin/munin-graph --cron $@ || exit 1
