- name: "Install ripe-atlas-tools"
  apt:
    name:
      - ripe-atlas-tools
      - ripe-atlas-tools-doc

- name: "Clean up old ripe-atlas virtualenv"
  file:
    path: /usr/share/ripe-atlas-venv
    state: absent
