- block:
  - name: Install packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - munin

  - name: copy munin-cron
    copy:
      src=munin-cron
      dest=/usr/bin/munin-cron
      owner=root
      group=root
      mode=0755

  - name: overwrite default cronjob
    template:
      src: cron.d/munin.j2
      dest: /etc/cron.d/munin

  - name: Create config files
    template:
      src: "{{ item }}"
      dest: /etc/munin/
      owner: root
      group: root
      mode: 0644
    with_items:
      - munin.conf
      - apache.conf
      - apache24.conf
    notify:
      - restart apache2

  - name: set apache config symlink
    file:
      src: /etc/munin/apache24.conf
      dest: /etc/apache2/conf-enabled/munin.conf
      state: link
      force: yes
    notify:
      - restart apache2

  - name: chown cgi-tmp
    file:
      path: /var/lib/munin/cgi-tmp
      state: directory
      owner: www-data
      group: www-data
      recurse: yes

  - name: enable services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - apache2
  tags:
    - munin-master
    - munin
