#!/usr/bin/env bash

userlist=/opt/graphite/users.list
tmpfile=/opt/graphite/.users.list

if [ -f $tmpfile ]; then
    rm $tmpfile
fi
for username in $(members ring-users); do
    passfile=/home/${username}/graphite.pass
    if [ -d $passfile ]; then
        >&2 echo "$passfile is a directory"
    fi
    if [ -f $passfile ]; then
        if [ $(head -1 $passfile) ]; then
            echo -n "$username:" >> $tmpfile
            head -1 $passfile >> $tmpfile
        fi
    fi
done
mv $tmpfile $userlist
