# Blacklist modules

# CopyFail: https://xint.io/blog/copy-fail-linux-distributions
blacklist algif_aead
install algif_aead /bin/false

# DirtyFrag: https://github.com/V4bel/dirtyfrag
install esp4 /bin/false
install esp6 /bin/false
install rxrpc /bin/false

# PinTheft: https://github.com/v12-security/pocs/tree/09e835b587bf71249775654061ae4c79e92cf430/pintheft
install rds /bin/false
install rds_tcp /bin/false

