# Blacklist modules

# https://xint.io/blog/copy-fail-linux-distributions
blacklist algif_aead
install algif_aead /bin/false

# https://github.com/V4bel/dirtyfrag
install esp4 /bin/false
install esp6 /bin/false
install rxrpc /bin/false
