#!/bin/sh 

case "$SSH_ORIGINAL_COMMAND" in 
*\&*) 
echo "Rejected" 
;; 
*\(*) 
echo "Rejected" 
;; 
*\{*) 
echo "Rejected" 
;; 
*\;*) 
echo "Rejected" 
;; 
*\<*) 
echo "Rejected" 
;; 
*\`*) 
echo "Rejected" 
;; 
*\|*) 
echo "Rejected" 
;; 
rsync\ --server\ --sender*) 
$SSH_ORIGINAL_COMMAND 
;; 
cat\ /etc/mtab)
$SSH_ORIGINAL_COMMAND
;;
*) 
echo "Rejected" 
;; 
esac 
