#!/usr/bin/env python3
#
# Check health of NLNOG Ring node
#
# Author: Martin Pels <martin@rodecker.nl>
#

import datetime
import json
import os
import re
import requests
import subprocess
import sys
import time

NODES='/etc/ansible/ring/nodes'
DOMAIN='ring.nlnog.net'
CRONPATH='/etc/cron.d/ansible'
LOGPATH='/var/log/ansible/ansible.log'
WEBPATH='/var/www/ring'
API4='95.211.149.25'
API6='[2001:1af8:4013::25]'
APIPATH='/1.0/health_report'
WEBTIMEOUT=122

def main(argv):
    result = dict()
    result['info'] = dict()
    health = dict()
    descriptions = dict()
    try:
        infranodes = get_infranodes()

        # System information
        result['info']['ubuntu_release'] = get_ubuntu_release()
        result['info']['virtualization'] = get_virtualization_type()

        # Filesystem checks
        health['mountstatus_root'] = check_mountstatus()
        descriptions['mountstatus_root'] = "The root filesystem is in read/write status"
        health['diskspace_root'] = check_diskspace()
        descriptions['diskspace_root'] = "The root filesystem has enough free disk space"

        # L3 connectivity checks
        health['ipv6_addresses'] = check_ipv6_addr()
        descriptions['ipv6_addresses'] = "The IPv6 address of the node matches the ring database"
        health['ipv6_gateway'] = check_ipv6_gw()
        descriptions['ipv6_gateway'] = "The IPv6 gateway is reachable"
        health['ipv6_reachability'] = check_ipv6_hosts(infranodes['V6'])
        descriptions['ipv6_reachability'] = "There is IPv6 connectivity beyond the gateway"
        health['ipv4_addresses'] = check_ipv4_addr()
        descriptions['ipv4_addresses'] = "The IPv4 address of the node matches the ring database"
        health['ipv4_gateway'] = check_ipv4_gw()
        descriptions['ipv4_gateway'] = "The IPv4 gateway is reachable"
        health['ipv4_reachability'] = check_ipv4_hosts(infranodes['V4'])
        descriptions['ipv4_reachability'] = "There is IPv4 connectivity beyond the gateway"

        # DNS checks
        health['dns_config'] = check_dnsconfig()
        descriptions['dns_config'] = "The local host is configured as DNS resolver"
        health['dns_resolvers'] = check_resolvers()
        descriptions['dns_resolvers'] = "The configured DNS resolvers are functioning"

        # NTP check
        health['ntp_status'] = check_ntp()
        descriptions['ntp_status'] = "NTP is running and the clock is synchronized"

        # SSHd check
        health['sshd_status'] = check_sshd()
        descriptions['sshd_status'] = "The SSH daemon is running"

        # HTTP/HTTPS checks
        health['https_github'] = check_weburl('https://github.com/')
        descriptions['https_github'] = "A webrequest for 'https://github.com/' succeeded"
        health['http_aptrepo_bit'] = check_weburl('http://ftp.bit.nl/ubuntu')
        descriptions['http_aptrepo_bit'] = "A webrequest for 'http://ftp.bit.nl/ubuntu' succeeded"
        health['http_aptrepo_ring'] = check_weburl('http://apt.ring.nlnog.net/deb/dists/ring/Release')
        descriptions['http_aptrepo_ring'] = "A webrequest for 'http://apt.ring.nlnog.net/deb/dists/ring/Release' succeeded"

        # Ansible checks
        health['ansible_cron'] = check_ansible_cron()
        descriptions['ansible_cron'] = "The ansible cron job is correctly configured"
        health['ansible_run'] = check_ansible_run()
        descriptions['ansible_run'] = "Ansible has recently run"

        result['info']['success'] = False
        for key in health:
            if health[key] == False:
                result['info']['success'] = False
                break
            else:
                result['info']['success'] = True
    except:
        result['info']['success'] = False

    # Post results to RING API
    health_api4 = report_health(4,{'info':result['info'],'health':health})
    health_api6 = report_health(6,{'info':result['info'],'health':health})
    health['ipv4_ringapi'] = health_api4
    descriptions['ipv4_ringapi'] = "Pushing this health report to the IPv4 ring API (https://" +API4+ "/) succeeded"
    health['ipv6_ringapi'] = health_api6
    descriptions['ipv6_ringapi'] = "Pushing this health report to the IPv6 ring API (https://" +API6+ "/) succeeded"
    if not health_api4 or not health_api6:
        result['info']['success'] = False

    # Store results on disk
    result['info']['last_check'] = datetime.datetime.now().isoformat()
    result['health'] = health
    result['descriptions'] = descriptions
    with open(WEBPATH + '/status.json', 'w') as of:
        json.dump(result, of, indent=2)
    of.close()

def get_infranodes(nodes_file=NODES):
    infranodes = dict()
    infranodes['V4'] = []
    infranodes['V6'] = []
    f = open(nodes_file,'r')
    for line in f:
        vars = line.split()
        if len(vars) < 3:
            continue
        if re.match('^.+\.infra\.' + DOMAIN + '$',vars[0]):
            for var in vars:
                if re.match('V[46]=.+', var):
                    (k, v) = var.split('=')
                    infranodes[k].append(v)
    f.close()
    return infranodes

def get_ubuntu_release():
    f = open('/etc/lsb-release','r')
    for line in f:
       m = re.match('^DISTRIB_RELEASE=(.+)$',line)
       if m:
           return m.group(1)
    return None

def get_virtualization_type():
    result = subprocess.run(['/usr/sbin/virt-what'],
                            stdout=subprocess.PIPE)
    for line in result.stdout.decode('utf-8').split('\n'):
        return line
    return None

def check_mountstatus(partition='/'):
    '''Partition is in read/write state'''
    f = open('/proc/mounts','r')
    for line in f:
        (fs,mp,fstype,optstr,dmp,ps) = line.split(' ')
        opts = optstr.split(',')
        if mp == partition and 'rw' in opts:
            return True
    return False

def check_diskspace(partition='/', maximum=99, imaximum=99):
    '''Percentage of used disk space on a partition'''
    space_free = False
    result = subprocess.run(['df', '-h'], stdout=subprocess.PIPE)
    for line in result.stdout.decode('utf-8').split('\n'):
        df = line.split()
        if len(df) < 6:
            continue
        percentage = df[4][:-1]
        if df[5] == partition and int(percentage) <= maximum:
            space_free = True

    inode_free = False
    result = subprocess.run(['df', '-i'], stdout=subprocess.PIPE)
    for line in result.stdout.decode('utf-8').split('\n'):
        df = line.split()
        if len(df) < 6:
            continue
        percentage = df[4][:-1]
        if df[5] == partition and int(percentage) <= imaximum:
            inode_free = True

    if space_free and inode_free:
        return True
    return False

def check_ipv6_addr():
    '''System must have a single, globally reachable IPv6 address'''
    address_count = 0
    result = subprocess.run(['ip', '-6', 'addr', 'list'],
                            stdout=subprocess.PIPE)
    for line in result.stdout.decode('utf-8').split('\n'):
        if not re.search('scope global', line):
            continue
        if re.search('inet6 f(c|d)', line):
            continue
        address_count = address_count + 1
    if address_count == 1:
        return True
    return False

def check_ipv6_gw():
    '''IPv6 gateway is reachable'''
    result = subprocess.run(['ip', '-6', 'route'],
                            stdout=subprocess.PIPE)
    for line in result.stdout.decode('utf-8').split('\n'):
        if not re.search('default', line) and not re.search('nexthop', line):
            continue
        route_vars = line.split()
        # Unnumbered gateway
        if route_vars[1] == 'dev':
            return True
        gw = route_vars[2]
        iface = route_vars[4]
        # Multiple next-hops
        if gw == 'ra' or gw == 'static':
            continue
        ping_result = subprocess.run(['ping6', '-c', '3', '-I', iface, gw],
                                     stdout=subprocess.PIPE)
        if ping_result.returncode == 0:
            return True
    return False

def check_ipv6_hosts(addresses,minimum=1):
    '''IPv6 addresses are pingable'''
    pingable = 0
    for address in addresses:
        ping_result = subprocess.run(['ping6', '-c', '3', address],
                                     stdout=subprocess.PIPE)
        if ping_result.returncode == 0:
            pingable = pingable + 1
    if pingable >= minimum:
        return True
    return False

def check_ipv4_addr():
    '''System must have a globally reachable IPv4 address'''
    address_count = 0
    result = subprocess.run(['ip', '-4', 'addr', 'list'],
                            stdout=subprocess.PIPE)
    for line in result.stdout.decode('utf-8').split('\n'):
        if not re.search('scope global', line):
            continue
        address_count = address_count + 1
    if address_count >= 1:
        return True
    return False

def check_ipv4_gw():
    '''IPv4 gateway is reachable'''
    result = subprocess.run(['ip', '-4', 'route'],
                            stdout=subprocess.PIPE)
    for line in result.stdout.decode('utf-8').split('\n'):
        if not re.search('default', line):
            continue
        route_vars = line.split()
        # Unnumbered gateway
        if route_vars[1] == 'dev':
            return True
        gw = route_vars[2]
        ping_result = subprocess.run(['ping', '-c', '3', gw],
                                     stdout=subprocess.PIPE)
        if ping_result.returncode == 0:
            return True
    return False

def check_ipv4_hosts(addresses,minimum=1):
    '''IPv4 addresses are pingable'''
    pingable = 0
    for address in addresses:
        ping_result = subprocess.run(['ping', '-c', '3', address],
                                     stdout=subprocess.PIPE)
        if ping_result.returncode == 0:
            pingable = pingable + 1
    if pingable >= minimum:
        return True
    return False

def get_nameservers():
    nameservers = []
    f = open('/etc/resolv.conf','r')
    for line in f:
        if not re.match('^nameserver\s.+',line):
            continue
        vars = line.split()
        if len(vars) < 2:
            continue
        nameservers.append(vars[1])
    return nameservers

def check_dnsconfig():
    '''Resolver points to localhost'''
    nameservers = get_nameservers()
    if len(nameservers) == 2 \
      and '127.0.0.1' in nameservers \
      and '::1' in nameservers:
        return True
    return False

def check_resolvers():
    '''Responsiveness of resolvers'''
    nameservers = get_nameservers()
    if len(nameservers) < 1:
        return False
    for ns in nameservers:
        dig_result = subprocess.run(['dig', '+short', '@' + ns,
                                     'ring.nlnog.net', 'AAAA'],
                                    stdout=subprocess.PIPE)
        if dig_result.returncode != 0:
            return False
        if len(dig_result.stdout.decode('utf-8')) < 1:
            return False
    return True

def check_ntp():
    '''Clock is synced with NTP'''
    ntp_result = subprocess.run(['ntpctl', '-s', 'status'],
                                 stdout=subprocess.PIPE)
    if ntp_result.returncode != 0:
        return False
    if re.search('clock synced',ntp_result.stdout.decode('utf-8')):
        return True
    return False

def check_sshd():
    '''SSH daemon is running'''
    sshd_result = subprocess.run(['/etc/init.d/ssh', 'status'],
                                 stdout=subprocess.PIPE)
    if sshd_result.returncode != 0:
        return False
    if re.search('Active: active \(running\)',sshd_result.stdout.decode('utf-8')):
        return True
    return False

def check_weburl(uri):
    '''Check HTTP/HTTPS reachability'''
    try:
        r = requests.get(uri,timeout=WEBTIMEOUT)
        if r.status_code == 200:
            return True
    except Exception:
        pass
    return False

def check_ansible_cron():
    '''Ansible cron status'''
    f = open(CRONPATH, 'r')
    for line in f:
        if re.match('^([*0-9/,]+\s){5}root\s/usr/local/sbin/ansible-cron\s.+$', line):
            return True
    return False

def check_ansible_run(age=21600):
    '''Time since last ansible run'''
    try:
        mtime = os.path.getmtime(LOGPATH)
    except OSError:
        return False
    if (time.time() - mtime) < age:
        return True
    return False

def report_health(family,health):
    '''Report health to RING API'''
    hostname = API4
    if family == 6:
        hostname = API6
    summary = json.dumps(health)
    try:
        r = requests.post('https://' + hostname + APIPATH, data=summary, timeout=WEBTIMEOUT, verify=False)
        j = json.loads(r.text)
        if j['info']['success'] == 1:
            return True
    except Exception:
        pass
    return False


if __name__ == "__main__":
        main(sys.argv)
