- name: "Install certbot"
  apt:
    name: python3-certbot-apache
    state: latest

- include_tasks: dbmaster.yml
  when: dbmaster == true

- include_tasks: dbbackup.yml
  when: dbbackup == true

- name: "Check for existing certificates"
  stat: path=/etc/letsencrypt/live/{{ item }}/cert.pem
  register: certs_installed
  with_items: "{{ letsencrypt_certs|default([]) }}"

- name: "Generate certificates"
  command: /usr/bin/certbot certonly --apache -n -d {{ item.item }} --agree-tos -m ring-admins@nlnog.net
  with_items: "{{ certs_installed.results }}"
  when: certs_installed.results is defined and item.stat is defined and item.stat.exists == False
