#!/usr/bin/env bash

TEMP=/tmp/answer$$
clean_up() {
  clear
  rm -f $TEMP
 exit
#  pkill -u ${UID}
}

launch_bird4() {

socket="/var/run/bird/bird.ctl"

clear 
echo -e "
NLNOG RING Looking Glass - ${HOSTNAME}
===============================================

You can issue commands like

Show detailed information for a prefix or IP: 

    \033[1mshow route for 85.184.184.1 all\033[0m

Show all routes originated by AS15562:

    \033[1mshow route where bgp_path.last = 15562\033[0m

Show all routes which have AS2914 in the path:

    \033[1mshow route where bgp_path ~ [= * 2914 * =]\033[0m

Equivalent of 'show bgp sum':

    \033[1mshow protocols\033[0m

have fun!
==============================================
$(birdc -s $socket show status | grep -vi ready )
"
/usr/sbin/birdc -s $socket -r
}

launch_bird6() {
clear
echo -e "
NLNOG RING Looking Glass - ${HOSTNAME}
===============================================

You can issue commands like

Show detailed information for a prefix or IP: 

    \033[1mshow route for 2001:67c:208c::1 all\033[0m

Show all routes originated by AS15562:

    \033[1mshow route where bgp_path.last = 15562\033[0m

Show all routes which have AS2914 in the path:

    \033[1mshow route where bgp_path ~ [= * 2914 * =]\033[0m

Equivalent of 'show bgp sum':

    \033[1mshow protocols\033[0m

have fun!
==============================================
$(birdc6 show status | grep -vi ready )
"
/usr/sbin/birdc6 -r
}

main_menu() {
	dialog \
	--backtitle "NLNOG RING Looking Glass: ${HOSTNAME}" \
	--menu "Choose a Looking Glass :" 10 70 4 \
	1 IPv4 \
	3 IPv6 \
	4 Logout 2>$TEMP
	choice=$(cat $TEMP)
	case $choice in
	    1) launch_bird4;;
	    3) launch_bird6;;
	    4) clean_up;;
	esac
}

while true
	do
		main_menu
	done
